version: '3.2'

networks:
  neo4j:
    driver: bridge

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WITH_XDEBUG=true
    working_dir: /opt/project
    networks:
      - neo4j
    volumes:
      - .:/opt/project
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - neo4j
    expose:
      - 9000
  neo4j:
    networks:
      - neo4j
    image: neo4j:4.2-enterprise
    healthcheck:
      test: [ "CMD", "neo4j status" ]
      interval: 30s
      timeout: 10s
      retries: 5
    expose:
      - 7474
      - 7687
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=none
      - NEO4J_dbms_default__database=neo4j
